### ISSUE TITLE
Add functions for combining multiple predicates

### ISSUE THREAD

**Issue by menelaos** [lodash/lodash-fp#19]
Would it be possible to add functions that take an array of predicates
and combine them into a single predicate?

This is related to https://github.com/lodash/lodash/issues/1072.
I don't know whether it makes sense to add this to the original `lodash`
but in a functional programming context this is fairly standard, cf.
Haskell's `and` and `or` or `allPass` and `anyPass` in RamdaJS.

**Comment by jdalton** [comment]
I want to do this too. If you want create pull request on lodash. You can use the names `and` and `or`.

**Comment by menelaos** [comment]
Sorry, I made a mistake...Haskell's `and` and `or` correspond to `every` and `some` in `lodash`. 
There is an open [PR](https://github.com/jashkenas/underscore/pull/2124) for underscore that implements this functionality. Might be worth contacting the [author](https://github.com/jridgewell).

**Comment by jdalton** [comment]
I know there may be others that was me attempting to encourage you to contribute ;)

**Comment by menelaos** [comment]
Fair enough ;-)
I'm just a bit insecure about submitting PRs to multi-million downloads/week projects :-)

**Comment by jdalton** [comment]
No worries, go for it! We're pretty easy going and will assist if needed.

**Comment by Ghoughpteighbteau** [comment]
If I can drop a thought here, can't we realistically say that a predicate is a type of a function? The lodash docs even say as much for _.negate, It expects predicates. Could you not consider having the ability to compose predicates be an aspect of the predicate type?

for example, `_.isNull.not().and(_.isString.not())`

```
_.isNull.not().and(_.isString.not())("lol");
// -> false
_.isNull.not().and(_.isString.not())({a:"lol"});
// -> true
_.isNull.not().and(_.isString.not())(undefined);
// -> true
_.isNull.not().and(_.isString.not())(null);
// -> false
```

This solves the naming issues.

**Comment by jdalton** [comment]
Thanks @Ghoughpteighbteau! I want to avoid augmenting method like that.

**Comment by Ghoughpteighbteau** [comment]
fair enough, it's just without something like this, then your namespacing becomes a flat list, and you have to deeply consider what you name what and how you categorize it. Maybe there are ways to subgroup things so that they don't become difficult to parse that I'm not aware of? 

As someone who's fairly new to lodash, I should mention from a newbie viewpoint that I feel like I get hit with a "wall" of functions, and teasing out what functions are relevant to my current task is *hard*. For example. If I want to test the value of a deep property, where should I look? In the object section? It's got `_.has`, in the utilities section? it has `_.property`.

See what I mean? You're fighting namespace pollution. Personally, I have no idea how else to mange something like that.

Anyway, thanks for your promptness and hard work @jdalton!
